
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

ecovacs:
  username: !secret email
  password: !secret deebot_password
  country: us
  continent: na

pi_hole:
  - host: IP_ADDRESS
